export const SET_USER = 'SET_USER'

export const SET_USERS = 'SET_USERS'

export const SET_CHANNEL = 'SET_CHANNEL'

export const SET_FAVOURITECHANNEL = 'SET_FAVOURITECHANNEL'

export const REMOVE_FAVOURITECHANNEL = 'REMOVE_FAVOURITECHANNEL'

export const UPDATE_CHANNEL_MEMBERS = 'UPDATE_CHANNEL_MEMBERS'

export const UPDATE_CHANNEL_ADMINS = 'UPDATE_CHANNEL_ADMINS'